
services:
  apiventory:
    build: .
    # image: ghcr.io/cosmo-tech/apiventory:latest
    restart: unless-stopped
    volumes:
      - ./inventory:/apiventory/_inventory/
      - ./_env:/apiventory/.env
